// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfP9qsDythIYmHebRcOFkHn3WSA3GShw',
    appId: '1:1093914611595:web:c4f29b0efccf29ec0f698e',
    messagingSenderId: '1093914611595',
    projectId: 'trackify-1b42c',
    authDomain: 'trackify-1b42c.firebaseapp.com',
    storageBucket: 'trackify-1b42c.firebasestorage.app',
    measurementId: 'G-KRVGD42R3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHUItPwMRcn74-Vi_mndc6n6NqeYWgYGs',
    appId: '1:1093914611595:android:40b38b034b333c1f0f698e',
    messagingSenderId: '1093914611595',
    projectId: 'trackify-1b42c',
    storageBucket: 'trackify-1b42c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyButcsW3N5Igj6ZFHzFsTSb38eMGny8r4s',
    appId: '1:1093914611595:ios:5b6816903ae2aa940f698e',
    messagingSenderId: '1093914611595',
    projectId: 'trackify-1b42c',
    storageBucket: 'trackify-1b42c.firebasestorage.app',
    androidClientId: '1093914611595-pvtkmb6asohtfm00tjb5j9s62r5s0h2o.apps.googleusercontent.com',
    iosClientId: '1093914611595-bl610j0rgsiulnvvbd6hsktp5shjnkm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyButcsW3N5Igj6ZFHzFsTSb38eMGny8r4s',
    appId: '1:1093914611595:ios:5b6816903ae2aa940f698e',
    messagingSenderId: '1093914611595',
    projectId: 'trackify-1b42c',
    storageBucket: 'trackify-1b42c.firebasestorage.app',
    androidClientId: '1093914611595-pvtkmb6asohtfm00tjb5j9s62r5s0h2o.apps.googleusercontent.com',
    iosClientId: '1093914611595-bl610j0rgsiulnvvbd6hsktp5shjnkm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcfP9qsDythIYmHebRcOFkHn3WSA3GShw',
    appId: '1:1093914611595:web:0c78cad6c57a05370f698e',
    messagingSenderId: '1093914611595',
    projectId: 'trackify-1b42c',
    authDomain: 'trackify-1b42c.firebaseapp.com',
    storageBucket: 'trackify-1b42c.firebasestorage.app',
    measurementId: 'G-ZK0KZPWNRC',
  );

}